# Site settings
title: CryptoPartyDC
description: The latest info on cryptoparties in Washington, D.C.
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Cryptoparty
user_description: Cryptoparty DC is a local edition of the global digital security community. This is a community-driven, community-owned learning group. We do not make money. We do not endorse products. We prefer the F/OSS solution, when it makes sense, over the commercially available.
user_title: Washington, D.C.
email: anon@anon.com
twitter_username: lorem_ipsum
github_username:  cryptopartydc
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
